name: flight_booking
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  go_router: ^14.6.3
  flutter_svg: ^2.0.17
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/font/metropolis/metropolis-ExtraLight.otf
          weight: 200
        - asset: assets/font/metropolis/metropolis-Light.otf
          weight: 300
        - asset: assets/font/metropolis/metropolis-Regular.otf
          weight: 400
        - asset: assets/font/metropolis/metropolis-Medium.otf
          weight: 500
        - asset: assets/font/metropolis/metropolis-SemiBold.otf
          weight: 600
        - asset: assets/font/metropolis/metropolis-Bold.otf
          weight: 700
        - asset: assets/font/metropolis/metropolis-ExtraBold.otf
          weight: 800
        - asset: assets/font/metropolis/metropolis-Black.otf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
